### PR TITLE
Respect bicycle route relations (Fixes #17)

### LINKED ISSUE #17: Unexpected cycling route from Nebringen to Herrenberg
## Expected behavior
Requesting a cycling route from Nebringen to Herrenberg should propose a route via Gültstein, as the official RadNETZ BW passes there.

## Observed behavior
Requesting a cycling route from [Nebringen to Herrenberg](https://pilot.mobil-in-herrenberg.de/reitti/Siedlerstraße%202%2C%20Gäufelden%3A%3A48.560420207973785%2C8.853178024291994/Richthofenstraße%2C%20Herrenberg%3A%3A48.59386747325061%2C8.867876529693605?modes=BICYCLE&time=1583736530) proposes a route via Haslach.

## Data sets in use (links to GTFS and OSM PBF files)
regbez-stuttgart
hb.tif

## Command line used to start OTP
N.a.
## Router config and graph build config JSON
```
{
  "osmWayPropertySet": "germany"
}
```
## Steps to reproduce the problem
N.a.

## Root causes
There are multiple probable causes for this issue:
* GermanyWayPropertySetSource evaluates lcn/rcn/ncn, but only if set on ways. bicycle route relations are not taken into account
* The OSM data currently contains only some touristic bicycle routes, but not yet the RadNETZ BW
* The weight for lcn/rcn/ncn might need to be adapted to prefer those ways

### PR DESCRIPTION
**Pull request by hbruch**
To be completed by pull request submitter:

- [x] **issue**: Link to or create an [issue](https://github.com/opentripplanner/OpenTripPlanner/issues) that describes the relevant feature or bug. Add [GitHub keywords](https://help.github.com/articles/closing-issues-using-keywords/) to this PR's description (e.g., `closes #45`).
- [x] **tests**: Have you added relevant test coverage? Are all the tests passing on [the continuous integration service (Travis CI)](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Developers-Guide.md#continuous-integration)?
- [x] **formatting**: Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Developers-Guide.md#code-style)? 
- [ ] **documentation**: No new configuration option
- [x] **changelog**: add a bullet point to the [changelog file](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Changelog.md) with description and link to the linked issue

### CODE REVIEW

File: src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java [hunk 1]
```diff
@@ -958,6 +963,41 @@ private void processRoad(OSMRelation relation) {
...
     }
 
+    /**
+     * Handle route=bicycle relations. Copies their network type to all way members.
+     *
+     * @param relation
+     * @author hbruch
+     * @see "https://wiki.openstreetmap.org/wiki/Tag:route%3Dbicycle"
+     */
+    private void processBicycleRoute(OSMRelation relation) {
```
Comment (leonardehrenfried) [inline src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java]: I would love to rewrite this using `Optional` and the stream API.

File: src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java [hunk 2]
```diff
@@ -958,6 +963,41 @@ private void processRoad(OSMRelation relation) {
...
+            case "lcn": setNetworkForAllMembers(relation, "lcn"); break;
+            case "rcn": setNetworkForAllMembers(relation, "rcn"); break;
+            case "ncn": setNetworkForAllMembers(relation, "ncn"); break;
+            // we treat networks without known network type like local networks
+            default: setNetworkForAllMembers(relation, "lcn"); break;
+        }
+    }
+
+    private void setNetworkForAllMembers(OSMRelation relation, String lcn) {
+        for (OSMRelationMember member : relation.getMembers()) {
```
Comment (leonardehrenfried) [inline src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java]: Again, in my (functional programmer) view this would more easily if we used the streams API rather than `continue`. I admit that it's a style thing.

**Review by leonardehrenfried — APPROVED** [review]
Looks good but hard to tell if there are unintended side effects.

One improvement I can think of would be to write a test against one of my micrographs. If you tell which scenario you want to improve then I can write the test. Is it the route from Nebringen to Herrenberg?

**Comment by leonardehrenfried** [comment]
I took the liberty to use one of my micrograph tests and the result is sobering: https://gist.github.com/leonardehrenfried/f5bd438064853b84f405744bfdc7d80a

If you route from Nebringen to Herrenberg you still get the route via Haslach.

I'm still going to merge this in so we can analyse further.
